name: Wrapper tests

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  test_wrapper:
    name: Test Python wrapper
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install BaseGraph C++ and Python libraries
        run: |
          git clone https://github.com/BaseGraph/BaseGraph.git
          cd BaseGraph
          cmake -B build
          cmake --build build
          cmake --install build --prefix=".local"
          echo "$(pwd)/.local" >> $GITHUB_PATH
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install .
          cd ..

      - name: Install extension
        run: pip install .

      - name: Import module and call function
        shell: bash
        run: python -c "import basegraph; basegraph.random.generate_gilbert_random_graph(10, 0.01)"
